export const bibleQuestions = [
  { id: 'q001', question: '亞伯蘭第一次聽到「離開本地本族父家」呼召時身在何地？', options: { A: '迦南', B: '哈蘭', C: '吾珥', D: '摩押' }, answer: 'C' },
  { id: 'q002', question: '摩西的岳父葉忒羅是何民族的祭司？', options: { A: '米甸人', B: '以東人', C: '亞瑪力人', D: '亞捫人' }, answer: 'A' },
  { id: 'q003', question: '約書亞過約旦河時，約櫃的位置在隊伍中哪裡？', options: { A: '最前', B: '中間', C: '最後', D: '分兩支隊' }, answer: 'A' },
  { id: 'q004', question: '撒母耳膏掃羅後，掃羅遇到幾個預兆？', options: { A: '一個', B: '二個', C: '三個', D: '四個' }, answer: 'C' },
  { id: 'q005', question: '大衛剪下掃羅衣角後「心中自責」的主因是？', options: { A: '冒犯王的受膏者', B: '背誓言', C: '恐懼報復', D: '欺騙同伴' }, answer: 'A' },
  { id: 'q006', question: '所羅門登基後求上帝的第一件事是？', options: { A: '財富', B: '智慧治理民事', C: '軍事勝利', D: '長壽' }, answer: 'B' },
  { id: 'q007', question: '以利亞在何山上與巴力先知爭論？', options: { A: '西乃山', B: '何烈山', C: '迦密山', D: '他泊山' }, answer: 'C' },
  { id: 'q008', question: '詩篇119篇的主要特徵？', options: { A: '最短', B: '最長', C: '沒標題', D: '含最多次「哈利路亞」' }, answer: 'B' },
  { id: 'q009', question: '「約拿」名字的希伯來詞義是？', options: { A: '鴿子', B: '魚', C: '審判', D: '赦免' }, answer: 'A' },
  { id: 'q010', question: '「奇妙策士、全能的神」出自以賽亞書哪章？', options: { A: '第7章', B: '第8章', C: '第9章', D: '第10章' }, answer: 'C' },
  { id: 'q011', question: '登山變相時出現的舊約人物？', options: { A: '以利亞與摩西', B: '以賽亞與耶利米', C: '亞伯拉罕與雅各', D: '但以理與以西結' }, answer: 'A' },
  { id: 'q012', question: '馬可福音開頭引用哪位先知？', options: { A: '瑪拉基', B: '以賽亞', C: '阿摩司', D: '撒迦利亞' }, answer: 'B' },
  { id: 'q013', question: '「我是初，我是終」首見於哪卷書？', options: { A: '創世記', B: '詩篇', C: '以賽亞書', D: '啟示錄' }, answer: 'C' },
  { id: 'q014', question: '七印的揭開者是？', options: { A: '長老', B: '羔羊', C: '天使長', D: '審判官' }, answer: 'B' },
  { id: 'q015', question: '「義人必因信得生」引自哪位先知？', options: { A: '哈巴谷', B: '彌迦', C: '以賽亞', D: '詩篇' }, answer: 'A' },
  { id: 'q016', question: '「愛是永不止息」出自哥林多前書第？章。', options: { A: '11', B: '12', C: '13', D: '14' }, answer: 'C' },
  { id: 'q017', question: '「沒有行為的信心」出自哪卷？', options: { A: '羅馬書', B: '雅各書', C: '希伯來書', D: '約翰一書' }, answer: 'B' },
  { id: 'q018', question: '耶穌洗彼得的腳時說「我若不洗你」下句是？', options: { A: '你仍屬我', B: '你就與我無份', C: '你必懊悔', D: '你將重生' }, answer: 'B' },
  { id: 'q019', question: '拿但業初見耶穌時被稱為？', options: { A: '無詭詐的以色列人', B: '有信心之人', C: '公義之人', D: '智慧之民' }, answer: 'A' },
  { id: 'q020', question: '啟示錄「不冷不熱」的教會是哪一個？', options: { A: '以弗所', B: '別迦摩', C: '老底嘉', D: '撒狄' }, answer: 'C' },
  { id: 'q021', question: '「耶和華以勒」意指？', options: { A: '主是醫治者', B: '主必預備', C: '主是平安', D: '主為我歌唱' }, answer: 'B' },
  { id: 'q022', question: '約瑟被賣給以實瑪利人時年齡？', options: { A: '15', B: '17', C: '20', D: '21' }, answer: 'B' },
  { id: 'q023', question: '出埃及的以色列人渡過紅海在經文中由誰帶領？', options: { A: '雲柱與火柱', B: '約書亞', C: '摩西之杖', D: '亞倫' }, answer: 'A' },
  { id: 'q024', question: '神降嗎哪於曠野是為了？', options: { A: '醫治百姓', B: '試驗信心順服', C: '給軍糧', D: '顯示能力' }, answer: 'B' },
  { id: 'q025', question: '以色列民要求立王的先知是？', options: { A: '以利亞', B: '撒母耳', C: '以利沙', D: '拿單' }, answer: 'B' },
  { id: 'q026', question: '撒母耳年幼時聽見呼召，共被呼叫幾次？', options: { A: '2 次', B: '3 次', C: '4 次', D: '5 次' }, answer: 'C' },
  { id: 'q027', question: '大衛取得歌利亞的武器後，放在何處？', options: { A: '他家中', B: '約櫃旁', C: '祭司家挪伯', D: '耶路撒冷城門' }, answer: 'C' },
  { id: 'q028', question: '所羅門聖殿奉獻禱告時，天上出現什麼徵兆？', options: { A: '雨虹', B: '火降與榮光充滿聖所', C: '烏鴉過頂', D: '雲霧四起' }, answer: 'B' },
  { id: 'q029', question: '以利沙醫治乃縵使用何方法？', options: { A: '告油', B: '七次沐浴於約旦河', C: '禱告吹氣', D: '以杖觸摸' }, answer: 'B' },
  { id: 'q030', question: '約拿逃避時坐船前往？', options: { A: '尼尼微', B: '他施', C: '耶帕', D: '哥林多' }, answer: 'B' },
  { id: 'q031', question: '詩篇中最短的篇章是哪一篇？', options: { A: '117篇', B: '131篇', C: '150篇', D: '1篇' }, answer: 'A' },
  { id: 'q032', question: '「地生青草」首次出現於創世記哪日？', options: { A: '第三日', B: '第四日', C: '第五日', D: '第六日' }, answer: 'A' },
  { id: 'q033', question: '挪亞方舟停在哪座山？', options: { A: '尼波山', B: '亞拉臘山', C: '西乃山', D: '以法蓮山' }, answer: 'B' },
  { id: 'q034', question: '神賜亞伯拉罕「以撒」這名之義為？', options: { A: '歡樂', B: '笑聲', C: '信心', D: '平安' }, answer: 'B' },
  { id: 'q035', question: '雅各改名以色列的意思為？', options: { A: '神的朋友', B: '與神摔跤得勝者', C: '被揀選的人', D: '平安之子' }, answer: 'B' },
  { id: 'q036', question: '摩西何時擊磐出水而被責備？', options: { A: '利非訂', B: '迦低斯曠野', C: '以琳', D: '西乃' }, answer: 'B' },
  { id: 'q037', question: '以利亞升天時以什麼帶走？', options: { A: '烈火車火馬', B: '暴雨風暴', C: '光雲', D: '天梯' }, answer: 'A' },
  { id: 'q038', question: '所羅門之子導致國度分裂者是？', options: { A: '羅波安', B: '耶羅波安', C: '約蘭', D: '約哈斯' }, answer: 'A' },
  { id: 'q039', question: '以賽亞書中「以馬內利」意思是？', options: { A: '神與我們同在', B: '永恆的生命', C: '耶和華醫治', D: '恩典的主' }, answer: 'A' },
  { id: 'q040', question: '但以理禁食三週吃什麼？', options: { A: '麵包與水', B: '素食不沾美酒肉', C: '蜜與蝗蟲', D: '全禁食' }, answer: 'B' },
  { id: 'q041', question: '耶穌受試探幾項？', options: { A: '二', B: '三', C: '四', D: '五' }, answer: 'B' },
  { id: 'q042', question: '耶穌驅逐鬼群「群」的名稱是？', options: { A: '教團', B: '群（Legion）', C: '軍隊', D: '會眾' }, answer: 'B' },
  { id: 'q043', question: '「山上寶訓」出自哪卷書？', options: { A: '路加福音', B: '馬太福音', C: '馬可福音', D: '約翰福音' }, answer: 'B' },
  { id: 'q044', question: '鬼入豬群的地點？', options: { A: '拿撒勒', B: '迦百農', C: '加大拉', D: '伯大尼' }, answer: 'C' },
  { id: 'q045', question: '耶穌平靜風浪時說的話是？', options: { A: '安靜吧，平靜吧！', B: '風止息吧！', C: '靜默無聲！', D: '安然無懼！' }, answer: 'A' },
  { id: 'q046', question: '十二門徒中職業為稅吏者？', options: { A: '猶大', B: '馬太', C: '多馬', D: '腓力' }, answer: 'B' },
  { id: 'q047', question: '「彼得」原名？', options: { A: '約瑟', B: '約拿的兒子西門', C: '利未', D: '撒該' }, answer: 'B' },
  { id: 'q048', question: '耶穌在何城行第一個神蹟？', options: { A: '拿撒勒', B: '迦百農', C: '迦拿', D: '伯大利' }, answer: 'C' },
  { id: 'q049', question: '五餅二魚餵飽多少男人？', options: { A: '約三千', B: '約五千', C: '約四千', D: '約六千' }, answer: 'B' },
  { id: 'q050', question: '耶穌騎入耶路撒冷所騎的是？', options: { A: '馬', B: '驢駒', C: '駱駝', D: '牛' }, answer: 'B' },
  { id: 'q051', question: '最先看見復活的耶穌的是誰？', options: { A: '彼得', B: '約翰', C: '抹大拉的馬利亞', D: '馬可' }, answer: 'C' },
  { id: 'q052', question: '耶穌升天前停留地點？', options: { A: '橄欖山', B: '拿撒勒', C: '伯大尼', D: '加利利' }, answer: 'A' },
  { id: 'q053', question: '五旬節聖靈降臨時有何現象？', options: { A: '烈火與方言', B: '雷霆與星光', C: '烏雲與閃電', D: '霧氣' }, answer: 'A' },
  { id: 'q054', question: '彼得在雞叫前否認主幾次？', options: { A: '一次', B: '兩次', C: '三次', D: '四次' }, answer: 'C' },
  { id: 'q055', question: '保羅原名？', options: { A: '撒羅', B: '掃羅', C: '沙希', D: '納坦' }, answer: 'B' },
  { id: 'q056', question: '保羅家鄉是哪裡？', options: { A: '加利利', B: '大數', C: '雅典', D: '羅馬' }, answer: 'B' },
  { id: 'q057', question: '保羅遇見主時在往哪裡的路上？', options: { A: '以色列', B: '大馬士革', C: '羅馬', D: '哥林多' }, answer: 'B' },
  { id: 'q058', question: '腓立比的獄卒信主後立刻做什麼？', options: { A: '禱告', B: '為他們洗傷', C: '奉獻金錢', D: '傳報官府' }, answer: 'B' },
  { id: 'q059', question: '提摩太的母親是信主的猶太婦人，名？', options: { A: '呂底亞', B: '以利沙伯', C: '友尼基', D: '喬安娜' }, answer: 'C' },
  { id: 'q060', question: '希伯來書作者強調耶穌為？', options: { A: '君王', B: '至高祭司', C: '創造主', D: '審判者' }, answer: 'B' },
  { id: 'q061', question: '啟示錄四騎士中「黑馬」象徵？', options: { A: '戰爭', B: '飢荒', C: '死亡', D: '勝利' }, answer: 'B' },
  { id: 'q062', question: '啟示錄獸的數字666象徵？', options: { A: '完全之數', B: '人的數目', C: '天使之號', D: '七印總和' }, answer: 'B' },
  { id: 'q063', question: '施洗約翰穿駱駝毛衣，用什麼為食？', options: { A: '蜜與蝗蟲', B: '麥餅', C: '野果', D: '酪與石蜜' }, answer: 'A' },
  { id: 'q064', question: '耶穌被釘十字架地點又名？', options: { A: '錫安山', B: '各各他', C: '他泊山', D: '伯特利' }, answer: 'B' },
  { id: 'q065', question: '羔羊的血塗門框象徵拯救哪事件？', options: { A: '亞伯拉罕之約', B: '逾越節脫埃及災', C: '猶大之約', D: '巴比倫被擄' }, answer: 'B' },
  { id: 'q066', question: '約書亞攻下耶利哥之後燒盡之外，留下？', options: { A: '喇合一家', B: '所有財寶', C: '城牆重建者', D: '祭司' }, answer: 'A' },
  { id: 'q067', question: '士師底波拉與哪位將軍同陣？', options: { A: '巴拉', B: '基甸', C: '耶弗他', D: '參孫' }, answer: 'A' },
  { id: 'q068', question: '撒母耳膏大衛時，大衛在做什麼？', options: { A: '放羊', B: '禱告', C: '彈琴奏樂', D: '打穀' }, answer: 'A' },
  { id: 'q069', question: '大衛被膏時在位於？', options: { A: '伯利恆', B: '耶路撒冷', C: '希伯崙', D: '迦特' }, answer: 'A' },
  { id: 'q070', question: '參孫之力來源是？', options: { A: '信仰神', B: '長髮未剃', C: '祭司膏油', D: '祭獻' }, answer: 'B' },
  { id: 'q071', question: '以斯帖記主角所屬民族是？', options: { A: '亞瑪力人', B: '以色列人', C: '猶太人', D: '米甸人' }, answer: 'C' },
  { id: 'q072', question: '但以理三友不拜金像的王是？', options: { A: '尼布甲尼撒', B: '伯沙撒', C: '古列', D: '大流士' }, answer: 'A' },
  { id: 'q073', question: '亞伯拉罕第一個築壇地點？', options: { A: '伯特利', B: '示劍', C: '希伯崙', D: '摩利樹岡' }, answer: 'D' },
  { id: 'q074', question: '雅各作夢天梯後命名該地為？', options: { A: '伯利恆', B: '伯特利', C: '迦南', D: '哈蘭' }, answer: 'B' },
  { id: 'q075', question: '摩西死於哪山？', options: { A: '尼波山', B: '西乃山', C: '何烈山', D: '他泊山' }, answer: 'A' },
  { id: 'q076', question: '約書亞死時年齡？', options: { A: '90', B: '100', C: '110', D: '120' }, answer: 'C' },
  { id: 'q077', question: '路得記中的路得來自？', options: { A: '摩押', B: '亞捫', C: '迦南', D: '以法蓮' }, answer: 'A' },
  { id: 'q078', question: '「神愛世人」出自哪卷？', options: { A: '路加', B: '馬太', C: '約翰', D: '馬可' }, answer: 'C' },
  { id: 'q079', question: '耶穌比喻「浪子回頭」出自哪卷？', options: { A: '約翰', B: '馬可', C: '路加', D: '馬太' }, answer: 'C' },
  { id: 'q080', question: '馬太的原名？', options: { A: '利未', B: '西門', C: '雅各', D: '腓力' }, answer: 'A' },
  { id: 'q081', question: '司提反被石頭打死時說的最後一句話？', options: { A: '父啊，赦免他們', B: '主耶穌，接收我的靈魂', C: '交託靈魂', D: '阿們' }, answer: 'B' },
  { id: 'q082', question: '保羅在雅典講道提及「未識之神」的祭壇在哪？', options: { A: '羅馬', B: '以弗所', C: '亞略巴古', D: '腓立比' }, answer: 'C' },
  { id: 'q083', question: '啟示錄結尾「主耶穌啊，我願你來！」出自誰說？', options: { A: '約翰', B: '長老', C: '天使', D: '保羅' }, answer: 'A' },
  { id: 'q084', question: '啟示錄最後一章章數？', options: { A: '20', B: '21', C: '22', D: '23' }, answer: 'C' },
  { id: 'q085', question: '以弗所書強調信徒是屬於？', options: { A: '光明之子', B: '國度子民', C: '教會身體', D: '祭司後裔' }, answer: 'C' },
  { id: 'q086', question: '羅馬書主題核心：', options: { A: '信心稱義', B: '律法公義', C: '教會管理', D: '聖靈恩賜' }, answer: 'A' },
  { id: 'q087', question: '加拉太書指出拯救不憑什麼？', options: { A: '信心', B: '律法行為', C: '愛心工', D: '救援使命' }, answer: 'B' },
  { id: 'q088', question: '提摩太後書中提到誰「愛現今的世界」？', options: { A: '亞歷山大', B: '低馬', C: '哥尼裡', D: '許勉' }, answer: 'B' },
  { id: 'q089', question: '約翰一書核心主題是？', options: { A: '光與黑暗', B: '愛與真理', C: '律與恩', D: '罪與贖' }, answer: 'B' },
  { id: 'q090', question: '猶大書篇數共？', options: { A: '一章', B: '二章', C: '三章', D: '四章' }, answer: 'A' },
  { id: 'q091', question: '亞伯拉罕原名？', options: { A: '亞伯蘭', B: '亞比蘭', C: '蘭伯拉', D: '亞巴' }, answer: 'A' },
  { id: 'q092', question: '以掃與雅各的關係？', options: { A: '父子', B: '兄弟', C: '表親', D: '叔侄' }, answer: 'B' },
  { id: 'q093', question: '約瑟在埃及被稱為？', options: { A: '撒拉法首相', B: '瑣安領袖', C: '撒法那忒巴內亞', D: '拉麥拉領袖' }, answer: 'C' },
  { id: 'q094', question: '聖靈降臨信徒舊約預言出自？', options: { A: '約珥書', B: '阿摩司書', C: '以賽亞書', D: '以西結書' }, answer: 'A' },
  { id: 'q095', question: '「主是我的牧者，我必不致缺乏」為哪篇詩篇？', options: { A: '22篇', B: '23篇', C: '24篇', D: '25篇' }, answer: 'B' },
  { id: 'q096', question: '馬利亞探望誰後一同讚頌神？', options: { A: '馬大', B: '以利沙伯', C: '撒羅米', D: '亞拿' }, answer: 'B' },
  { id: 'q097', question: '主禱文開頭稱呼神為？', options: { A: '天上的君王', B: '我們在天上的父', C: '永恆之主', D: '慈悲的神' }, answer: 'B' },
  { id: 'q098', question: '約翰啟示錄中「新天新地」出現在第？章。', options: { A: '20', B: '21', C: '22', D: '19' }, answer: 'B' },
  { id: 'q099', question: '耶穌被釘時十字架上方牌寫的是？', options: { A: '猶太人的王耶穌', B: '神之子耶穌', C: '拯救世人者', D: '拿撒勒人耶穌' }, answer: 'D' },
  { id: 'q100', question: '聖經最後一句話是？', options: { A: '主耶穌啊，願你快來', B: '願主耶穌的恩惠常與眾聖徒同在', C: '阿們', D: '榮耀歸主' }, answer: 'B' }
];

const toPublicQuestion = (question) => ({
  id: question.id,
  question: question.question,
  options: Object.entries(question.options).map(([key, text]) => ({ key, text }))
});

export const drawBibleQuestion = () => {
  const question = bibleQuestions[Math.floor(Math.random() * bibleQuestions.length)];
  return toPublicQuestion(question);
};

export const isBibleAnswerCorrect = (questionId, answer) => {
  const question = bibleQuestions.find((item) => item.id === questionId);
  return Boolean(question && question.answer === String(answer || '').trim().toUpperCase());
};
